name: process_limeseg_env
channels:
  - conda-forge
dependencies:
  - python=3.7 
  - vedo
  - open3d
  - pymeshfix
  - numpy
  - scikit-image
  - pandas
  - matplotlib
  - scikit-scan
  - scikit-morphology
